### ISSUE TITLE
Help required in adding wordpress plugin

### ISSUE THREAD

**Issue by shashank1511** [CodeKitchenBV/Thumbor#1]
Hi,

I want to use thumbor plugin in my wordpress, can you please provide me the steps for adding the plugin in my wordpress.

Thanks
Shashank

**Comment by markoheijnen** [comment]
You do have a Thumbor installation running which is requirement for this plugin?

**Comment by shashank1511** [comment]
@markoheijnen Yes I do have.

**Comment by markoheijnen** [comment]
Sorry for the delay. Currently what you need to do except activating is added two defines in your wp-config.php file.

```
define( 'THUMBOR_SERVER', 'https://thumborserver' );
define( 'THUMBOR_SECRET', 'your secret' );
```
